# This is a basic workflow to help you get started with Actions

name: CI 2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes and create a PR
      pull-requests: write # Required to create/update a pull request

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full git history is fetched

      # Runs a single command using the runners shell
      - name: changes to a file
        run: |
          echo "Updated content at $(date)" >> version.txt
          cat version.txt

      # Runs a set of commands using the runners shell
      - name: Create a File
        run: |
          echo "Hello World DLam was here" > file1.txt
          cat file1.txt 
      
      - name: Create a new pull request with changes
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update version.txt with new date
          title: '[Automated] Update version.txt file'
          body: |
            This is an auto-generated pull request to update the `version.txt` file.
          branch: update-version-action_3 # The branch to create the PR from
          base: main # The branch to merge changes into
          labels: automated-pr, documentation
          draft: false